from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtMultimedia as M
class Ui_rail(object):
    def setupUi(self, rail):
        rail.setObjectName("rail")
        rail.resize(1228, 945)
        self.centralwidget = QtWidgets.QWidget(rail)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1241, 951))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Railway Announcement\\Test\\0.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 40, 351, 71))
        self.label_2.setText("")
        self.movie = QtGui.QMovie("D:\\Railway Announcement\\Test\\3.gif")
        self.label_2.setMovie(self.movie)
        self.movie.start()
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 135, 1241, 561))
        self.label_3.setText("")
        self.movie = QtGui.QMovie("D:\\Railway Announcement\\Test\\1.gif")
        self.label_3.setMovie(self.movie)
        self.movie.start()
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 10, 451, 121))
        self.label_4.setText("")
        self.movie = QtGui.QMovie("D:\\Railway Announcement\\Test\\26.gif")
        self.label_4.setMovie(self.movie)
        self.movie.start()
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 710, 41, 61))
        self.label_5.setText("")
        self.movie = QtGui.QMovie("D:\\Railway Announcement\\Test\\69.png")
        self.label_5.setMovie(self.movie)
        self.movie.start()
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(590, 820, 51, 41))
        self.label_6.setText("")
        self.movie = QtGui.QMovie("D:\\Railway Announcement\\Test\\27.gif")
        self.label_6.setMovie(self.movie)
        self.movie.start()
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(540, 780, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"border-color: rgb(0, 0, 0);\n"
"padding-left:27px;\n"
"padding-right:20px;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 870, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-color: rgb(85, 85, 85);")
        self.pushButton.setObjectName("pushButton")
        rail.setCentralWidget(self.centralwidget)
        self.retranslateUi(rail)
        QtCore.QMetaObject.connectSlotsByName(rail)
    def retranslateUi(self, rail):
        _translate = QtCore.QCoreApplication.translate
        rail.setWindowTitle(_translate("rail", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("rail", "Enter Location"))
        self.pushButton.setText(_translate("rail", "Search"))
        self.pushButton.clicked.connect(self.play)
        self.url = QtCore.QUrl.fromLocalFile('D:/Railway Announcement/Ui/Final_Gujarat.Gujarati.mp3')
        self.content = M.QMediaContent(self.url)
        self.player = M.QMediaPlayer()
        self.player.setMedia(self.content)
        self.pushButton.setText(_translate("rail", "Search"))
    def play(self):
        self.player.play()
        name = self.lineEdit.text()
        print(name)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rail = QtWidgets.QMainWindow()
    ui = Ui_rail()
    ui.setupUi(rail)
    rail.show()
    sys.exit(app.exec_())